### ISSUE TITLE
Docker for this project

### ISSUE THREAD

**Issue by larsvankleef** [stackkit/mocker-installer#7]
Example
```yaml
version: '3.1'
services:
  db:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=supersecret
     - MYSQL_DATABASE=mocker
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
```
